% generación menu grafico
h0 = figure('Units','points', ...
	'Color',[1 1 1], ...
	'MenuBar','none', ...
	'Name','Desarrollo del proceso', ...
	'NumberTitle','off', ...
	'Position',[120 255 250 50], ...
   'ToolBar','none');
h1 = uimenu('Parent',h0, ...
	'Label','Graficas datos En&trenamiento', ...
	'Tag','uimenu1');
h2 = uimenu('Parent',h1, ...
	'Label','C&iclo', ...
   'Tag','Subuimenu1',...
   'callback','grafent1');
h2 = uimenu('Parent',h1, ...
	'Label','&Tendencia', ...
   'Tag','Subuimenu1',...
   'callback','grafent2');
h2 = uimenu('Parent',h1, ...
	'Label','Ir&regularidad', ...
   'Tag','Subuimenu1',...
   'callback','grafent3');
h2 = uimenu('Parent',h1, ...
	'Label','R&ecuperación', ...
   'Tag','Subuimenu1',...
   'callback','grafent4');
h1 = uimenu('Parent',h0, ...
	'Label','Graficas datos &Validación', ...
	'Tag','uimenu1');
h2 = uimenu('Parent',h1, ...
	'Label','C&iclo', ...
   'Tag','Subuimenu1',...
   'callback','grafval1');
h2 = uimenu('Parent',h1, ...
	'Label','&Tendencia', ...
   'Tag','Subuimenu1',...
   'callback','grafval2');
h2 = uimenu('Parent',h1, ...
	'Label','Ir&regularidad', ...
   'Tag','Subuimenu1',...
   'callback','grafval3');
h2 = uimenu('Parent',h1, ...
	'Label','R&ecuperación serie', ...
   'Tag','Subuimenu1',...
   'callback','grafval4');
% creación botones
h1 = uicontrol(gcf, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'Callback','close all,save actual;paramet', ...
	'ListboxTop',0, ...
	'Position',[50 15 67 14], ...
   'String','Parametros RNA', ...
   'Tag','Pushbutton1');

h1 = uicontrol(gcf, ...
	'Units','points', ...
	'BackgroundColor',[0.752941176470588 0.752941176470588 0.752941176470588], ...
	'Callback','close', ...
	'ListboxTop',0, ...
	'Position',[150 15 50.75 14], ...
   'String','salir y salvar', ...
   'Callback','close all;save actual;princip',...
   'Tag','Pushbutton1');
% borrado de variables
clear ci2 red net a
clear ascens ascension asuncion bd cartag corpus dia dia1 dia2 
clear diaf diaf2 diames e emil emiliani fec1 fecha fechasmoviles 
clear fiestarel fiesta finmes h0 h1 i mesasu mescorpus mesf mesf2 
clear messyp n oblig pascua pascua1 patrias raza relig reyes 
clear sagrada sagrado sant semanasanta stfestivo1 stfestivo syp  
clear sypd
clear E Q a alfa ano ano1 ano2 ano3 ans bdfiestas cadena cantdia 
clear cota d d1 desv diacero dias dias2 fech1 festivo inf j k len
clear m mes mes1 mes2 mes3 mesascens mesf3 mesfestivo messagrado 
clear moviles sagrad sjose tam tama tamano tamano1 tamanof tipof 
%clear vectro w pesos1 pesos2 pesosentrena pesosobj pesosseriet