%clear all
close all
h0=figure;
tred=2;fentre=4;fapre=2;nc=5;tc1=10;tc2=10;tc3=10;tc4=10;
tc5=10;fc1=2;fc2=2;fc3=2;fc4=2;fc5=2;
periodo=1;p=2;tmaxc=15; numc=nc;
%pause
epocas=2000;goal=0.01;lr=0.1;
set(h0,'name','Seleccion de casos')
set(h0,'menubar','none');
set(h0,'numbertitle','off');
set(h0,'position',[80 125 600 400]);
set(h0,'color',[1 1 1]);
h1 = uimenu('Parent',h0, ...
	'Label','Selección de p&arametros de entrenamiento', ...
	'Tag','uimenu1');
h2 = uimenu('Parent',h1, ...
	'Label','&Manual', ...
   'Tag','Subuimenu1',...
   'callback','habilita');
h2 = uimenu('Parent',h1, ...
	'Label','&Automatico', ...
   'Tag','Subuimenu1',...
   'callback','tred=2;fentre=4;fapre=2;nc=5;tc1=10;tc2=10;tc3=10;tc4=10;tc5=10;fc1=2;fc2=2;fc3=2;fc4=2;fc5=2;p=1;close all;questdlg(''Se usara una Red Feed forward,fcn de entrenamiento gradiente descendente con momento,Regla de aprendizaje backpropagation con momento, 5 capas todas de 10 neuronas activadas mediante la función tansig'',''caracteristicas red'',''continuar'',''abandonar'');entre;');
h2 = uimenu('Parent',h1, ...
	'Label','&Todos', ...
   'Tag','Subuimenu1',...
   'callback','pruebagca');
h1 = uimenu('Parent',h0, ...
	'Label','Ajustes a&vanzados', ...
	'Tag','uimenu1');
h2 = uimenu('Parent',h1, ...
	'Label','&Ajustes', ...
   'Tag','Subuimenu1',...
   'callback','ajust');

h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[21.75 271.75 100.25 15], ...
	'Style','text', ...
   'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','Tipo de red a utilizar');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[21.75 253 120.25 15], ...
   'Style','text', ...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','Función de entrenamiento',...
   'Tag','StaticText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[21.75 231.25 120.25 15], ...
	'Style','text', ...
   'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','Regla de aprendizaje');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[21.75 210.5 160.25 15], ...
	'Style','text', ...
   'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','Numero de capas sección oculta');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[21.75 190 250.25 15], ...
	'Style','text', ...
   'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','Selección de parametros para la red oculta');
hr = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[175 275.5 195 12], ...
	'String',' ', ...
	'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'string','Red Elmam|Feed forward|Feed forward en cascada',...
   'Callback','tred=get(hr,''value'');', ...
   'enable','off',...
	'Value',tred);
he = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[175 256.75 195 12], ...
	'String',' ', ...
   'Style','popupmenu', ...
   'string','Algoritmo de gradiente descendente (traingd)|Algoritmo de Leven Marquardt (trainlm)|Algoritmo Back Resilente (trainrp)|Algoritmo gradiente descendente con momento (traingdm)',...
   'Callback','fentre=get(he,''value'');', ...
   'Tag','PopupMenu1', ...
   'enable','off',...
	'Value',fentre);
ha = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[175 235 195 12], ...
	'String',' ', ...
   'Style','popupmenu', ...
   'string','Regla de aprendizaje backpropagación|Regla de aprendizaje backpropagación con momento',...
   'Callback','fapre=get(ha,''value'');', ...
   'enable','off',...
	'Tag','PopupMenu1', ...
	'Value',fapre);

hc = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[175 210 24 19.5], ...
   'Style','edit', ...
   'Callback','nc=eval(get(hc,''string''));', ...
   'Tag','EditText1',...
   'enable','off',...
   'value',nc);
hb1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[200.25 209.25 104.25 20.25], ...
   'Tag','Pushbutton1',...
   'string','Guardar',...
   'enable','off',...
   'callback','frame');
% botones de la Interfase
ent = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[93.75 5.25 104.25 20.25], ...
   'Tag','Pushbutton1',...
   'string','Entrenar',...
   'enable','on',...
   'callback','clc,close,entre');
salir = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[236.75 5.25 104.25 20.25], ...
   'Tag','Pushbutton1',...
   'enable','on',...
   'string','Salir',...
   'callback','clear,clc,close');
% datos capa 1
hfc1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[280 175 87 12], ...
	'String',' ', ...
	'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'string','logsig|tansig|hard line',...
   'enable','off',...
   'Callback','fc1=get(hfc1,''value'');', ...   
   'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[32 175 80.25 12], ...
	'Style','text', ...
	'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','Tamaño capa 1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[175 175 100 12], ...
	'Style','text', ...
	'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','F activación capa 1');
htc1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
   'Position',[124.5 175 35 12], ...
   'String',' ', ...
	'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'string','1|2|3|4|5|6|7|8|9|10|11|12|13|14|15',...
   'enable','off',...
   'callback','tc1=(get(htc1,''value''));');
% datos capa 2
htc2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 160 35 12], ...
   'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'string','1|2|3|4|5|6|7|8|9|10|11|12|13|14|15',...
   'enable','off',...
   'callback','tc2=(get(htc2,''value''));',...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[175 160 100 12], ...
	'Style','text', ...
	'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','F.activación capa 2');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[32 160 82.5 12], ...
	'Style','text', ...
	'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','Tamaño capa 2');
hfc2 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[280 160 87 12], ...
	'String',' ', ...
	'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'string','logsig|tansig|hard line',...
   'Callback','fc2=get(hfc2,''value'');', ...   
   'enable','off',...
   'Value',1);

% selección datos capa 3
hfc3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[280 145 87 12], ...
	'String',' ', ...
	'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'enable','off',...
   'string','logsig|tansig|hard line',...
   'Callback','fc3=get(hfc3,''value'');', ...   
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[32 145 82.5 12], ...
	'Style','text', ...
	'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','Tamaño capa 3');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[175 145 100 12], ...
	'Style','text', ...
	'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','F.activación capa 3');
htc3 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 145 35 12], ...
   'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'string','1|2|3|4|5|6|7|8|9|10|11|12|13|14|15',...   
   'enable','off',...
   'callback','tc3=(get(htc3,''value''));',...
   'Tag','EditText1');

% parametros capa 4
htc4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 130 35 12], ...
   'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'string','1|2|3|4|5|6|7|8|9|10|11|12|13|14|15',...
   'enable','off',...
   'callback','tc4=(get(htc4,''value''));',...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[175 130 100 12], ...
	'Style','text', ...
	'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','F.activación capa 4');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[32 130 80.25 12], ...
	'Style','text', ...
	'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','Tamaño capa 4');
hfc4 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[280 130 87 12], ...
	'String',' ', ...
   'Style','popupmenu', ...
   'enable','off',...
   'Tag','PopupMenu1', ...
     'Callback','fc4=get(hfc4,''value'');', ...   
   'string','logsig|tansig|hard line',...
   'Value',1);


%parametros capa 5

hfc5 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[280 115 87 12], ...
	'String',' ', ...
	'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'string','logsig|tansig|hard line',...
   'enable','off',...
   'Callback','fc5=get(hfc5,''value'');', ...   
	'Value',1);
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[32 115 82.5 12], ...
	'Style','text', ...
	'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','Tamaño capa 5');
h1 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'ListboxTop',0, ...
	'Position',[175 115 100 12], ...
	'Style','text', ...
	'Tag','StaticText1',...
   'fontname','MS Sans Serif',...
   'fontsize',10,...
   'BackgroundColor',[1 1 1],...
   'HorizontalAlignment','left',...
   'string','F.activación capa 5');
htc5 = uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'ListboxTop',0, ...
	'Position',[124.5 115 35 12], ...
   'Style','popupmenu', ...
   'Tag','PopupMenu1', ...
   'string','1|2|3|4|5|6|7|8|9|10|11|12|13|14|15',...
   'enable','off',...
   'callback','tc5=(get(htc5,''value''));',...
   'Tag','EditText1');

% se removio la definicón de las capas 6-10 se llevo a remocion

%if nargout > 0, fig = h0; end
%clc
%clear h* ent salir